indexing
	description: "Generated by h2e from the file %
		%C:\EOpenGL\src0.43\test\egl\gl_test_2\build\resource.h."

class
	APPLICATION_RESOURCES

feature -- Access

	Eiffel_opengl_icon_id: INTEGER is 102
	Opengl_info_dialog_id: INTEGER is 103

end -- class APPLICATION_RESOURCES
