/* 
 * EGLUT.H
 *
 * desciption: "Header file for EGLUT.C"
 * library: "EGLUT - Eiffel wrapping of the OpenGL GLUT library"
 * compilers: "SmallEiffel -0.74 beta #17 (lcc-win32 3.7)"
 * author: "Paul Cohen"
 * copyright: "Copyright (c) 2002 Paul Cohen, see file forum.txt"
 * date: "$Date: 2002/11/25 16:09:30 $"
 * revision: "$Revision: 1.1 $"
 */

#ifndef __EGLUT__
#define __EGLUT__

/* Include SmallEiffels header file containing definitions of EIF_OBJ etc. */
#include <base.h>

/* Function prototype for the Eiffel function to be called from all callback functions. 
   NOTE! This prototype was originally generated by compiling with (SmallEiffel) a 
   cecil file containing the following lines:
   -- Name of h file to create:
   eglut_application.h
   -- name of feature to be called from eglut:
   mac	EGLUT_APPLICATION	main_application_callback */
void mac(void* C,T2 a1,T2 a2,T2 a3,T2 a4,T2 a5,T3 a6);

/* Include the generated Cecil header file that is generated for every EGLUT 
   application. It contaisn the function prototype for the Eiffel function
   that all the glut callback functions will call! */
/*#include "eglut_application.h" */

#ifndef __glut_h__
#include <glut.h>
#endif

/* Callback event constants */
#define EGLUT_DISPLAY_EVENT 1
#define EGLUT_RESHAPE_EVENT 2
#define EGLUT_KEYBOARD_EVENT 3
#define EGLUT_MOUSE_EVENT 4
#define EGLUT_MOTION_EVENT 5
#define EGLUT_PASSIVE_MOTION_EVENT 6
#define EGLUT_VISIBILITY_EVENT 7
#define EGLUT_ENTRY_EVENT 8
#define EGLUT_SPECIAL_EVENT 9
#define EGLUT_IDLE_EVENT 10

/* Set macros for the callback functions */
/* glutDisplayFunc(NULL) is illegal! */
#define eglut_set_display_func glutDisplayFunc(eglut_display_function)
#define eglut_set_reshape_func_to_null glutReshapeFunc(NULL)
#define eglut_set_reshape_func glutReshapeFunc(eglut_reshape_function)
#define eglut_set_keyboard_func_to_null glutKeyboardFunc(NULL)
#define eglut_set_keyboard_func glutKeyboardFunc(eglut_keyboard_function)
#define eglut_set_motion_func_to_null glutMotionFunc(NULL)
#define eglut_set_motion_func glutMotionFunc(eglut_motion_function)
#define eglut_set_passive_motion_func_to_null glutPassiveMotionFunc(NULL)
#define eglut_set_passive_motion_func glutPassiveMotionFunc(eglut_passive_motion_function)
#define eglut_set_mouse_func_to_null glutMouseFunc(NULL)
#define eglut_set_mouse_func glutMouseFunc(eglut_mouse_function)
#define eglut_set_visibility_func_to_null glutVisibilityFunc(NULL)
#define eglut_set_visibility_func glutVisibilityFunc(eglut_visibility_function)
#define eglut_set_entry_func_to_null glutEntryFunc(NULL)
#define eglut_set_entry_func glutEntryFunc(eglut_entry_function)
#define eglut_set_special_func_to_null glutSpecialFunc(NULL)
#define eglut_set_special_func glutSpecialFunc(eglut_special_function)
#define eglut_set_idle_func_to_null glutIdleFunc(NULL)
#define eglut_set_idle_func glutIdleFunc(eglut_idle_function)

/* Set macro for the EGLUT_APPLICATION object */
#define eglut_set_application_object(_addr_) (eglut_app=(EIF_OBJ)_addr_) 

/* Address of the Eiffel object EGLUT_APPLICATION created for each application. */
/* extern EIF_OBJ eglut_app; */
EIF_OBJ eglut_app;

/* Macro for quitting the application */
#define eglut_quit(_exitcode_) exit(_exitcode_)

/* EGLUT global function prototypes */
void eglut_display_function (void);
void eglut_reshape_function (int, int);
void eglut_keyboard_function (unsigned char, int, int);
void eglut_motion_function (int, int);
void eglut_passive_motion_function (int, int);
void eglut_mouse_function (int, int, int, int);
void eglut_visibility_function (int);
void eglut_entry_function (int);
void eglut_special_function (int, int, int);
void eglut_idle_function (void);

#endif

